# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

connection_create <- function(host, user, password, db, port, unix_socket, client_flag, groups, default_file, ssl_key, ssl_cert, ssl_ca, ssl_capath, ssl_cipher) {
    .Call(`_RMariaDB_connection_create`, host, user, password, db, port, unix_socket, client_flag, groups, default_file, ssl_key, ssl_cert, ssl_ca, ssl_capath, ssl_cipher)
}

connection_valid <- function(con) {
    .Call(`_RMariaDB_connection_valid`, con)
}

connection_release <- function(con) {
    invisible(.Call(`_RMariaDB_connection_release`, con))
}

connection_info <- function(con) {
    .Call(`_RMariaDB_connection_info`, con)
}

connection_quote_string <- function(con, input) {
    .Call(`_RMariaDB_connection_quote_string`, con, input)
}

connection_begin_transaction <- function(con) {
    invisible(.Call(`_RMariaDB_connection_begin_transaction`, con))
}

connection_commit <- function(con) {
    invisible(.Call(`_RMariaDB_connection_commit`, con))
}

connection_rollback <- function(con) {
    invisible(.Call(`_RMariaDB_connection_rollback`, con))
}

connection_is_transacting <- function(con) {
    .Call(`_RMariaDB_connection_is_transacting`, con)
}

driver_init <- function() {
    invisible(.Call(`_RMariaDB_driver_init`))
}

driver_done <- function() {
    invisible(.Call(`_RMariaDB_driver_done`))
}

version <- function() {
    .Call(`_RMariaDB_version`)
}

init_logging <- function(log_level) {
    invisible(.Call(`_RMariaDB_init_logging`, log_level))
}

result_create <- function(con, sql) {
    .Call(`_RMariaDB_result_create`, con, sql)
}

result_column_info <- function(rs) {
    .Call(`_RMariaDB_result_column_info`, rs)
}

result_fetch <- function(rs, n) {
    .Call(`_RMariaDB_result_fetch`, rs, n)
}

result_bind <- function(rs, params) {
    invisible(.Call(`_RMariaDB_result_bind`, rs, params))
}

result_release <- function(rs) {
    invisible(.Call(`_RMariaDB_result_release`, rs))
}

result_rows_affected <- function(rs) {
    .Call(`_RMariaDB_result_rows_affected`, rs)
}

result_rows_fetched <- function(rs) {
    .Call(`_RMariaDB_result_rows_fetched`, rs)
}

result_complete <- function(rs) {
    .Call(`_RMariaDB_result_complete`, rs)
}

result_active <- function(rs) {
    .Call(`_RMariaDB_result_active`, rs)
}

